<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TheCleanArch.Application" Version="0.1.0-rc0006" />
  </ItemGroup>

  <ItemGroup Condition=" '$(UseDomainDrivenDesign)' == 'true' ">
    <ProjectReference Include="..\Domain\TheCleanArch.Templates.Solution.Domain.csproj" />
  </ItemGroup>

</Project>
