<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="TheCleanArch.InterfaceAdapter" Version="0.1.0-rc0006" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAdapter\TheCleanArch.Templates.Solution.DataAdapter.csproj" />
    <ProjectReference Include="..\Application\TheCleanArch.Templates.Solution.Application.csproj" />
  </ItemGroup>

</Project>
