<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition=" '$(LayerIsEnterprise)' " Include="TheCleanArch.Enterprise" Version="0.1.0-rc*" />
    <PackageReference Condition=" '$(LayerIsApplication)' " Include="TheCleanArch.Application" Version="0.1.0-rc*" />
    <PackageReference Condition=" '$(LayerIsInterfaceAdapter)' " Include="TheCleanArch.InterfaceAdapter" Version="0.1.0-rc*" />
    <PackageReference Condition=" '$(LayerIsExternal)' " Include="TheCleanArch.Core" Version="0.1.0-rc*" />
  </ItemGroup>

</Project>
